site_name: dtps-http
nav:
- Home: index.md
- Concepts: concepts.md
- Protocol: protocol.md
- Client tutorial: client-tutorial.md
- Server tutorial: server-tutorial.md
- Server: server.md
- Client: client.md
- About:
  - about.md

#theme: readthedocs
theme:
  name: material

plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [src]
        load_external_modules: true
        show_if_no_docstring: true
        show_docstring_description: true
        show_docstring_examples: true
        show_docstring_other_parameters: true
        show_docstring_parameters: true
        show_docstring_return_type: true
        show_docstring_type_annotations: true
        show_source: true
        show_docstring_raises: true
        show_docstring_returns: true
        docstring_section_style: spacy
- search
- autorefs


extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#- https://cdn.jsdelivr.net/npm/mathjax/es5/mml-chtml.min.js
#- https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML
#- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/startup.js
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.superfences
- markdown.extensions.toc:
    permalink: true
- pymdownx.arithmatex:
    generic: true
watch:
- src
