[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool]
[tool.poetry]
name = "dtps-http"
version = "1.4.5"
description = ""
authors = ["Andrea Censi <AndreaCensi@users.noreply.github.com>"]
packages = [
    { from = "src", include = "dtps" },
    { from = "src", include = "dtps_http" },
    { from = "src", include = "dtps_http_programs" },
]

include = [
    { path = "src/dtps_http/static/**", format = ['sdist', 'wheel'] }
]

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = ">=3.6,<4"
cbor2 = ">=5.0,<6"
tcp_latency = "0.0.12"
typing_extensions = ">=3.7"
pymdown-extensions = ">=8,<10"
aiopubsub = ">=2,<4"
methodtools = "^0.4"
pydantic = ">=1.8,<2"
psutil = ">=5.6,<6"
urllib3 = ">=1.25,<2"
jsonpatch = ">=1.32,<2"
dataclasses = { version = "^0.8", python = "<3.7" }
async_generator = { version = "^1.10", python = "<3.7" }
async_exit_stack = { version = "^1.0", python = "<3.7" }


# other dependencies: aiohttp-devtools pre-commit mkdocs mkdocs-material mkdocstrings[python]
# pip install "mkdocstrings[python]"  mkdocs-material
timeout-decorator = "^0.5.0"
prettyprinter = "^0.18.0"
xxhash = ">=2.0,<4"

[tool.poetry.scripts]

dtps-http-py-server-example-clock = 'dtps_http_programs:clock_main'
dtps-http-py-server = 'dtps_http_programs:server_main'
dtps-http-py-client-stats = 'dtps_http_programs:dtps_stats_main'
dtps-http-py-proxy = 'dtps_http_programs:dtps_proxy_main'
dtps-http-py-send-continuous = 'dtps_http_programs:dtps_send_continuous_main'
dtps-http-py-listen= 'dtps_http_programs:dtps_listen_main'
dtps-http-py= 'dtps_http_programs:dtps_main'


[tool.poetry-dynamic-versioning]
enable = true
dirty = false
metadata = false
tagged-metadata = false
vcs = "git"
style = "pep440"
strict = false



[tool.poetry-dynamic-versioning.substitution]
folders = [
    { path = "src" }
]
