version: 2.1

jobs:
  "python-38":
    docker:
    - image: cimg/python:3.8
    steps:
    - run: python3 -m pip install nose2
    - run: python3 -m pip install -e .
    - run: nose2 python
  "python-310":
    docker:
    - image: cimg/python:3.10
    steps:
    - run: python3 -m pip install nose2
    - run: python3 -m pip install -e .
    - run: nose2 python
  build:
    docker:
      - image: cimg/rust:1.70.0
    steps:
      - checkout
      - run: cargo --version
      - run: apt-get update && apt-get install python3-pip
      - run: python3 -m pip install -e .
      - run:
          name: Run Tests
          command: "cargo test"
