[package]
name = "dtps_server_demo"
version = "0.1.0"
authors = ["Your Name <your_email@example.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
warp = "0.3.5"
tungstenite = "0.19"

maplit = "1.0.2"
uuid = { version = "0.8", features = ["v4"] } # // features v4 is for random (version 4) UUIDs
